/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as OurTeamImport } from './routes/our-team'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as FaqsImport } from './routes/faqs'
import { Route as ContactImport } from './routes/contact'
import { Route as BuyCryptoImport } from './routes/buy-crypto'
import { Route as AboutImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as RefRefIdImport } from './routes/ref/$refId'
import { Route as DashboardWithdrawHistoryImport } from './routes/dashboard/withdraw-history'
import { Route as DashboardTransferHistoryImport } from './routes/dashboard/transfer-history'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardReferralsImport } from './routes/dashboard/referrals'
import { Route as DashboardPlansImport } from './routes/dashboard/plans'
import { Route as DashboardNotificationsImport } from './routes/dashboard/notifications'
import { Route as DashboardLiquidationHistoryImport } from './routes/dashboard/liquidation-history'
import { Route as DashboardInvestmentHistoryImport } from './routes/dashboard/investment-history'
import { Route as DashboardDepositHistoryImport } from './routes/dashboard/deposit-history'
import { Route as DashboardAllHistoryImport } from './routes/dashboard/all-history'
import { Route as AdminWithdrawalsImport } from './routes/admin/withdrawals'
import { Route as AdminTransfersImport } from './routes/admin/transfers'
import { Route as AdminLiquidationsImport } from './routes/admin/liquidations'
import { Route as AdminInvestmentsImport } from './routes/admin/investments'
import { Route as AdminDepositsImport } from './routes/admin/deposits'
import { Route as DashboardWithdrawIndexImport } from './routes/dashboard/withdraw/index'
import { Route as DashboardTransferIndexImport } from './routes/dashboard/transfer/index'
import { Route as DashboardDepositIndexImport } from './routes/dashboard/deposit/index'
import { Route as DashboardAccountIndexImport } from './routes/dashboard/account/index'
import { Route as AdminWalletsIndexImport } from './routes/admin/wallets/index'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminProductsIndexImport } from './routes/admin/products/index'
import { Route as AdminPlansIndexImport } from './routes/admin/plans/index'
import { Route as AdminKycIndexImport } from './routes/admin/kyc/index'
import { Route as AdminCategoriesIndexImport } from './routes/admin/categories/index'
import { Route as DashboardAccountWalletImport } from './routes/dashboard/account/wallet'
import { Route as DashboardAccountProfileImport } from './routes/dashboard/account/profile'
import { Route as AdminWalletsNewImport } from './routes/admin/wallets/new'
import { Route as AdminProductsNewImport } from './routes/admin/products/new'
import { Route as AdminPlansNewImport } from './routes/admin/plans/new'
import { Route as AdminKycKycIdImport } from './routes/admin/kyc/$kycId'
import { Route as AdminCategoriesNewImport } from './routes/admin/categories/new'
import { Route as DashboardAccountLiquidateIndexImport } from './routes/dashboard/account/liquidate/index'
import { Route as DashboardAccountKycIndexImport } from './routes/dashboard/account/kyc/index'
import { Route as DashboardAccountKycRejectedImport } from './routes/dashboard/account/kyc/rejected'
import { Route as DashboardAccountKycPendingImport } from './routes/dashboard/account/kyc/pending'
import { Route as DashboardAccountKycNotSubmittedImport } from './routes/dashboard/account/kyc/not-submitted'
import { Route as DashboardAccountKycApprovedImport } from './routes/dashboard/account/kyc/approved'
import { Route as DashboardAccountInvestPlanIdImport } from './routes/dashboard/account/invest/$planId'
import { Route as AdminProductsEditProductIdImport } from './routes/admin/products/edit/$productId'
import { Route as AdminPlansEditPlanIdImport } from './routes/admin/plans/edit/$planId'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const OurTeamRoute = OurTeamImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const FaqsRoute = FaqsImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const BuyCryptoRoute = BuyCryptoImport.update({
  id: '/buy-crypto',
  path: '/buy-crypto',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const RefRefIdRoute = RefRefIdImport.update({
  id: '/ref/$refId',
  path: '/ref/$refId',
  getParentRoute: () => rootRoute,
} as any)

const DashboardWithdrawHistoryRoute = DashboardWithdrawHistoryImport.update({
  id: '/withdraw-history',
  path: '/withdraw-history',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardTransferHistoryRoute = DashboardTransferHistoryImport.update({
  id: '/transfer-history',
  path: '/transfer-history',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardReferralsRoute = DashboardReferralsImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPlansRoute = DashboardPlansImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardNotificationsRoute = DashboardNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardLiquidationHistoryRoute =
  DashboardLiquidationHistoryImport.update({
    id: '/liquidation-history',
    path: '/liquidation-history',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardInvestmentHistoryRoute = DashboardInvestmentHistoryImport.update(
  {
    id: '/investment-history',
    path: '/investment-history',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
)

const DashboardDepositHistoryRoute = DashboardDepositHistoryImport.update({
  id: '/deposit-history',
  path: '/deposit-history',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAllHistoryRoute = DashboardAllHistoryImport.update({
  id: '/all-history',
  path: '/all-history',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AdminWithdrawalsRoute = AdminWithdrawalsImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminTransfersRoute = AdminTransfersImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminLiquidationsRoute = AdminLiquidationsImport.update({
  id: '/liquidations',
  path: '/liquidations',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminInvestmentsRoute = AdminInvestmentsImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminDepositsRoute = AdminDepositsImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardWithdrawIndexRoute = DashboardWithdrawIndexImport.update({
  id: '/withdraw/',
  path: '/withdraw/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardTransferIndexRoute = DashboardTransferIndexImport.update({
  id: '/transfer/',
  path: '/transfer/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardDepositIndexRoute = DashboardDepositIndexImport.update({
  id: '/deposit/',
  path: '/deposit/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAccountIndexRoute = DashboardAccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AdminWalletsIndexRoute = AdminWalletsIndexImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductsIndexRoute = AdminProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminPlansIndexRoute = AdminPlansIndexImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminKycIndexRoute = AdminKycIndexImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCategoriesIndexRoute = AdminCategoriesIndexImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardAccountWalletRoute = DashboardAccountWalletImport.update({
  id: '/account/wallet',
  path: '/account/wallet',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAccountProfileRoute = DashboardAccountProfileImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AdminWalletsNewRoute = AdminWalletsNewImport.update({
  id: '/wallets/new',
  path: '/wallets/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductsNewRoute = AdminProductsNewImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminPlansNewRoute = AdminPlansNewImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminKycKycIdRoute = AdminKycKycIdImport.update({
  id: '/kyc/$kycId',
  path: '/kyc/$kycId',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCategoriesNewRoute = AdminCategoriesNewImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardAccountLiquidateIndexRoute =
  DashboardAccountLiquidateIndexImport.update({
    id: '/account/liquidate/',
    path: '/account/liquidate/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardAccountKycIndexRoute = DashboardAccountKycIndexImport.update({
  id: '/account/kyc/',
  path: '/account/kyc/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAccountKycRejectedRoute =
  DashboardAccountKycRejectedImport.update({
    id: '/account/kyc/rejected',
    path: '/account/kyc/rejected',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardAccountKycPendingRoute = DashboardAccountKycPendingImport.update(
  {
    id: '/account/kyc/pending',
    path: '/account/kyc/pending',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
)

const DashboardAccountKycNotSubmittedRoute =
  DashboardAccountKycNotSubmittedImport.update({
    id: '/account/kyc/not-submitted',
    path: '/account/kyc/not-submitted',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardAccountKycApprovedRoute =
  DashboardAccountKycApprovedImport.update({
    id: '/account/kyc/approved',
    path: '/account/kyc/approved',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardAccountInvestPlanIdRoute =
  DashboardAccountInvestPlanIdImport.update({
    id: '/account/invest/$planId',
    path: '/account/invest/$planId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const AdminProductsEditProductIdRoute = AdminProductsEditProductIdImport.update(
  {
    id: '/products/edit/$productId',
    path: '/products/edit/$productId',
    getParentRoute: () => AdminRouteRoute,
  } as any,
)

const AdminPlansEditPlanIdRoute = AdminPlansEditPlanIdImport.update({
  id: '/plans/edit/$planId',
  path: '/plans/edit/$planId',
  getParentRoute: () => AdminRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/buy-crypto': {
      id: '/buy-crypto'
      path: '/buy-crypto'
      fullPath: '/buy-crypto'
      preLoaderRoute: typeof BuyCryptoImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/liquidations': {
      id: '/admin/liquidations'
      path: '/liquidations'
      fullPath: '/admin/liquidations'
      preLoaderRoute: typeof AdminLiquidationsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/all-history': {
      id: '/dashboard/all-history'
      path: '/all-history'
      fullPath: '/dashboard/all-history'
      preLoaderRoute: typeof DashboardAllHistoryImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/deposit-history': {
      id: '/dashboard/deposit-history'
      path: '/deposit-history'
      fullPath: '/dashboard/deposit-history'
      preLoaderRoute: typeof DashboardDepositHistoryImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/investment-history': {
      id: '/dashboard/investment-history'
      path: '/investment-history'
      fullPath: '/dashboard/investment-history'
      preLoaderRoute: typeof DashboardInvestmentHistoryImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/liquidation-history': {
      id: '/dashboard/liquidation-history'
      path: '/liquidation-history'
      fullPath: '/dashboard/liquidation-history'
      preLoaderRoute: typeof DashboardLiquidationHistoryImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/plans': {
      id: '/dashboard/plans'
      path: '/plans'
      fullPath: '/dashboard/plans'
      preLoaderRoute: typeof DashboardPlansImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/transfer-history': {
      id: '/dashboard/transfer-history'
      path: '/transfer-history'
      fullPath: '/dashboard/transfer-history'
      preLoaderRoute: typeof DashboardTransferHistoryImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/withdraw-history': {
      id: '/dashboard/withdraw-history'
      path: '/withdraw-history'
      fullPath: '/dashboard/withdraw-history'
      preLoaderRoute: typeof DashboardWithdrawHistoryImport
      parentRoute: typeof DashboardRouteImport
    }
    '/ref/$refId': {
      id: '/ref/$refId'
      path: '/ref/$refId'
      fullPath: '/ref/$refId'
      preLoaderRoute: typeof RefRefIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/kyc/$kycId': {
      id: '/admin/kyc/$kycId'
      path: '/kyc/$kycId'
      fullPath: '/admin/kyc/$kycId'
      preLoaderRoute: typeof AdminKycKycIdImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/plans/new': {
      id: '/admin/plans/new'
      path: '/plans/new'
      fullPath: '/admin/plans/new'
      preLoaderRoute: typeof AdminPlansNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/wallets/new': {
      id: '/admin/wallets/new'
      path: '/wallets/new'
      fullPath: '/admin/wallets/new'
      preLoaderRoute: typeof AdminWalletsNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/account/profile': {
      id: '/dashboard/account/profile'
      path: '/account/profile'
      fullPath: '/dashboard/account/profile'
      preLoaderRoute: typeof DashboardAccountProfileImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/wallet': {
      id: '/dashboard/account/wallet'
      path: '/account/wallet'
      fullPath: '/dashboard/account/wallet'
      preLoaderRoute: typeof DashboardAccountWalletImport
      parentRoute: typeof DashboardRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/kyc/': {
      id: '/admin/kyc/'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/plans/': {
      id: '/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/wallets/': {
      id: '/admin/wallets/'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/deposit/': {
      id: '/dashboard/deposit/'
      path: '/deposit'
      fullPath: '/dashboard/deposit'
      preLoaderRoute: typeof DashboardDepositIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/transfer/': {
      id: '/dashboard/transfer/'
      path: '/transfer'
      fullPath: '/dashboard/transfer'
      preLoaderRoute: typeof DashboardTransferIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/withdraw/': {
      id: '/dashboard/withdraw/'
      path: '/withdraw'
      fullPath: '/dashboard/withdraw'
      preLoaderRoute: typeof DashboardWithdrawIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/admin/plans/edit/$planId': {
      id: '/admin/plans/edit/$planId'
      path: '/plans/edit/$planId'
      fullPath: '/admin/plans/edit/$planId'
      preLoaderRoute: typeof AdminPlansEditPlanIdImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/products/edit/$productId': {
      id: '/admin/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/admin/products/edit/$productId'
      preLoaderRoute: typeof AdminProductsEditProductIdImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/account/invest/$planId': {
      id: '/dashboard/account/invest/$planId'
      path: '/account/invest/$planId'
      fullPath: '/dashboard/account/invest/$planId'
      preLoaderRoute: typeof DashboardAccountInvestPlanIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/kyc/approved': {
      id: '/dashboard/account/kyc/approved'
      path: '/account/kyc/approved'
      fullPath: '/dashboard/account/kyc/approved'
      preLoaderRoute: typeof DashboardAccountKycApprovedImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/kyc/not-submitted': {
      id: '/dashboard/account/kyc/not-submitted'
      path: '/account/kyc/not-submitted'
      fullPath: '/dashboard/account/kyc/not-submitted'
      preLoaderRoute: typeof DashboardAccountKycNotSubmittedImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/kyc/pending': {
      id: '/dashboard/account/kyc/pending'
      path: '/account/kyc/pending'
      fullPath: '/dashboard/account/kyc/pending'
      preLoaderRoute: typeof DashboardAccountKycPendingImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/kyc/rejected': {
      id: '/dashboard/account/kyc/rejected'
      path: '/account/kyc/rejected'
      fullPath: '/dashboard/account/kyc/rejected'
      preLoaderRoute: typeof DashboardAccountKycRejectedImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/kyc/': {
      id: '/dashboard/account/kyc/'
      path: '/account/kyc'
      fullPath: '/dashboard/account/kyc'
      preLoaderRoute: typeof DashboardAccountKycIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/account/liquidate/': {
      id: '/dashboard/account/liquidate/'
      path: '/account/liquidate'
      fullPath: '/dashboard/account/liquidate'
      preLoaderRoute: typeof DashboardAccountLiquidateIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminLiquidationsRoute: typeof AdminLiquidationsRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminKycKycIdRoute: typeof AdminKycKycIdRoute
  AdminPlansNewRoute: typeof AdminPlansNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminWalletsNewRoute: typeof AdminWalletsNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminKycIndexRoute: typeof AdminKycIndexRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWalletsIndexRoute: typeof AdminWalletsIndexRoute
  AdminPlansEditPlanIdRoute: typeof AdminPlansEditPlanIdRoute
  AdminProductsEditProductIdRoute: typeof AdminProductsEditProductIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDepositsRoute: AdminDepositsRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminLiquidationsRoute: AdminLiquidationsRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminKycKycIdRoute: AdminKycKycIdRoute,
  AdminPlansNewRoute: AdminPlansNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminWalletsNewRoute: AdminWalletsNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminKycIndexRoute: AdminKycIndexRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWalletsIndexRoute: AdminWalletsIndexRoute,
  AdminPlansEditPlanIdRoute: AdminPlansEditPlanIdRoute,
  AdminProductsEditProductIdRoute: AdminProductsEditProductIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAllHistoryRoute: typeof DashboardAllHistoryRoute
  DashboardDepositHistoryRoute: typeof DashboardDepositHistoryRoute
  DashboardInvestmentHistoryRoute: typeof DashboardInvestmentHistoryRoute
  DashboardLiquidationHistoryRoute: typeof DashboardLiquidationHistoryRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPlansRoute: typeof DashboardPlansRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTransferHistoryRoute: typeof DashboardTransferHistoryRoute
  DashboardWithdrawHistoryRoute: typeof DashboardWithdrawHistoryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountProfileRoute: typeof DashboardAccountProfileRoute
  DashboardAccountWalletRoute: typeof DashboardAccountWalletRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardDepositIndexRoute: typeof DashboardDepositIndexRoute
  DashboardTransferIndexRoute: typeof DashboardTransferIndexRoute
  DashboardWithdrawIndexRoute: typeof DashboardWithdrawIndexRoute
  DashboardAccountInvestPlanIdRoute: typeof DashboardAccountInvestPlanIdRoute
  DashboardAccountKycApprovedRoute: typeof DashboardAccountKycApprovedRoute
  DashboardAccountKycNotSubmittedRoute: typeof DashboardAccountKycNotSubmittedRoute
  DashboardAccountKycPendingRoute: typeof DashboardAccountKycPendingRoute
  DashboardAccountKycRejectedRoute: typeof DashboardAccountKycRejectedRoute
  DashboardAccountKycIndexRoute: typeof DashboardAccountKycIndexRoute
  DashboardAccountLiquidateIndexRoute: typeof DashboardAccountLiquidateIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAllHistoryRoute: DashboardAllHistoryRoute,
  DashboardDepositHistoryRoute: DashboardDepositHistoryRoute,
  DashboardInvestmentHistoryRoute: DashboardInvestmentHistoryRoute,
  DashboardLiquidationHistoryRoute: DashboardLiquidationHistoryRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPlansRoute: DashboardPlansRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTransferHistoryRoute: DashboardTransferHistoryRoute,
  DashboardWithdrawHistoryRoute: DashboardWithdrawHistoryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountProfileRoute: DashboardAccountProfileRoute,
  DashboardAccountWalletRoute: DashboardAccountWalletRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardDepositIndexRoute: DashboardDepositIndexRoute,
  DashboardTransferIndexRoute: DashboardTransferIndexRoute,
  DashboardWithdrawIndexRoute: DashboardWithdrawIndexRoute,
  DashboardAccountInvestPlanIdRoute: DashboardAccountInvestPlanIdRoute,
  DashboardAccountKycApprovedRoute: DashboardAccountKycApprovedRoute,
  DashboardAccountKycNotSubmittedRoute: DashboardAccountKycNotSubmittedRoute,
  DashboardAccountKycPendingRoute: DashboardAccountKycPendingRoute,
  DashboardAccountKycRejectedRoute: DashboardAccountKycRejectedRoute,
  DashboardAccountKycIndexRoute: DashboardAccountKycIndexRoute,
  DashboardAccountLiquidateIndexRoute: DashboardAccountLiquidateIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/our-team': typeof OurTeamRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/liquidations': typeof AdminLiquidationsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/all-history': typeof DashboardAllHistoryRoute
  '/dashboard/deposit-history': typeof DashboardDepositHistoryRoute
  '/dashboard/investment-history': typeof DashboardInvestmentHistoryRoute
  '/dashboard/liquidation-history': typeof DashboardLiquidationHistoryRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transfer-history': typeof DashboardTransferHistoryRoute
  '/dashboard/withdraw-history': typeof DashboardWithdrawHistoryRoute
  '/ref/$refId': typeof RefRefIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/kyc/$kycId': typeof AdminKycKycIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/wallets/new': typeof AdminWalletsNewRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/wallet': typeof DashboardAccountWalletRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/kyc': typeof AdminKycIndexRoute
  '/admin/plans': typeof AdminPlansIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/wallets': typeof AdminWalletsIndexRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/deposit': typeof DashboardDepositIndexRoute
  '/dashboard/transfer': typeof DashboardTransferIndexRoute
  '/dashboard/withdraw': typeof DashboardWithdrawIndexRoute
  '/admin/plans/edit/$planId': typeof AdminPlansEditPlanIdRoute
  '/admin/products/edit/$productId': typeof AdminProductsEditProductIdRoute
  '/dashboard/account/invest/$planId': typeof DashboardAccountInvestPlanIdRoute
  '/dashboard/account/kyc/approved': typeof DashboardAccountKycApprovedRoute
  '/dashboard/account/kyc/not-submitted': typeof DashboardAccountKycNotSubmittedRoute
  '/dashboard/account/kyc/pending': typeof DashboardAccountKycPendingRoute
  '/dashboard/account/kyc/rejected': typeof DashboardAccountKycRejectedRoute
  '/dashboard/account/kyc': typeof DashboardAccountKycIndexRoute
  '/dashboard/account/liquidate': typeof DashboardAccountLiquidateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/our-team': typeof OurTeamRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/liquidations': typeof AdminLiquidationsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/all-history': typeof DashboardAllHistoryRoute
  '/dashboard/deposit-history': typeof DashboardDepositHistoryRoute
  '/dashboard/investment-history': typeof DashboardInvestmentHistoryRoute
  '/dashboard/liquidation-history': typeof DashboardLiquidationHistoryRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transfer-history': typeof DashboardTransferHistoryRoute
  '/dashboard/withdraw-history': typeof DashboardWithdrawHistoryRoute
  '/ref/$refId': typeof RefRefIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/kyc/$kycId': typeof AdminKycKycIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/wallets/new': typeof AdminWalletsNewRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/wallet': typeof DashboardAccountWalletRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/kyc': typeof AdminKycIndexRoute
  '/admin/plans': typeof AdminPlansIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/wallets': typeof AdminWalletsIndexRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/deposit': typeof DashboardDepositIndexRoute
  '/dashboard/transfer': typeof DashboardTransferIndexRoute
  '/dashboard/withdraw': typeof DashboardWithdrawIndexRoute
  '/admin/plans/edit/$planId': typeof AdminPlansEditPlanIdRoute
  '/admin/products/edit/$productId': typeof AdminProductsEditProductIdRoute
  '/dashboard/account/invest/$planId': typeof DashboardAccountInvestPlanIdRoute
  '/dashboard/account/kyc/approved': typeof DashboardAccountKycApprovedRoute
  '/dashboard/account/kyc/not-submitted': typeof DashboardAccountKycNotSubmittedRoute
  '/dashboard/account/kyc/pending': typeof DashboardAccountKycPendingRoute
  '/dashboard/account/kyc/rejected': typeof DashboardAccountKycRejectedRoute
  '/dashboard/account/kyc': typeof DashboardAccountKycIndexRoute
  '/dashboard/account/liquidate': typeof DashboardAccountLiquidateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/our-team': typeof OurTeamRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/liquidations': typeof AdminLiquidationsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/all-history': typeof DashboardAllHistoryRoute
  '/dashboard/deposit-history': typeof DashboardDepositHistoryRoute
  '/dashboard/investment-history': typeof DashboardInvestmentHistoryRoute
  '/dashboard/liquidation-history': typeof DashboardLiquidationHistoryRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transfer-history': typeof DashboardTransferHistoryRoute
  '/dashboard/withdraw-history': typeof DashboardWithdrawHistoryRoute
  '/ref/$refId': typeof RefRefIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/kyc/$kycId': typeof AdminKycKycIdRoute
  '/admin/plans/new': typeof AdminPlansNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/wallets/new': typeof AdminWalletsNewRoute
  '/dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/dashboard/account/wallet': typeof DashboardAccountWalletRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/kyc/': typeof AdminKycIndexRoute
  '/admin/plans/': typeof AdminPlansIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/wallets/': typeof AdminWalletsIndexRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/deposit/': typeof DashboardDepositIndexRoute
  '/dashboard/transfer/': typeof DashboardTransferIndexRoute
  '/dashboard/withdraw/': typeof DashboardWithdrawIndexRoute
  '/admin/plans/edit/$planId': typeof AdminPlansEditPlanIdRoute
  '/admin/products/edit/$productId': typeof AdminProductsEditProductIdRoute
  '/dashboard/account/invest/$planId': typeof DashboardAccountInvestPlanIdRoute
  '/dashboard/account/kyc/approved': typeof DashboardAccountKycApprovedRoute
  '/dashboard/account/kyc/not-submitted': typeof DashboardAccountKycNotSubmittedRoute
  '/dashboard/account/kyc/pending': typeof DashboardAccountKycPendingRoute
  '/dashboard/account/kyc/rejected': typeof DashboardAccountKycRejectedRoute
  '/dashboard/account/kyc/': typeof DashboardAccountKycIndexRoute
  '/dashboard/account/liquidate/': typeof DashboardAccountLiquidateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/buy-crypto'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/our-team'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/deposits'
    | '/admin/investments'
    | '/admin/liquidations'
    | '/admin/transfers'
    | '/admin/withdrawals'
    | '/dashboard/all-history'
    | '/dashboard/deposit-history'
    | '/dashboard/investment-history'
    | '/dashboard/liquidation-history'
    | '/dashboard/notifications'
    | '/dashboard/plans'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/transfer-history'
    | '/dashboard/withdraw-history'
    | '/ref/$refId'
    | '/admin/'
    | '/dashboard/'
    | '/admin/categories/new'
    | '/admin/kyc/$kycId'
    | '/admin/plans/new'
    | '/admin/products/new'
    | '/admin/wallets/new'
    | '/dashboard/account/profile'
    | '/dashboard/account/wallet'
    | '/admin/categories'
    | '/admin/kyc'
    | '/admin/plans'
    | '/admin/products'
    | '/admin/users'
    | '/admin/wallets'
    | '/dashboard/account'
    | '/dashboard/deposit'
    | '/dashboard/transfer'
    | '/dashboard/withdraw'
    | '/admin/plans/edit/$planId'
    | '/admin/products/edit/$productId'
    | '/dashboard/account/invest/$planId'
    | '/dashboard/account/kyc/approved'
    | '/dashboard/account/kyc/not-submitted'
    | '/dashboard/account/kyc/pending'
    | '/dashboard/account/kyc/rejected'
    | '/dashboard/account/kyc'
    | '/dashboard/account/liquidate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buy-crypto'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/our-team'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/deposits'
    | '/admin/investments'
    | '/admin/liquidations'
    | '/admin/transfers'
    | '/admin/withdrawals'
    | '/dashboard/all-history'
    | '/dashboard/deposit-history'
    | '/dashboard/investment-history'
    | '/dashboard/liquidation-history'
    | '/dashboard/notifications'
    | '/dashboard/plans'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/transfer-history'
    | '/dashboard/withdraw-history'
    | '/ref/$refId'
    | '/admin'
    | '/dashboard'
    | '/admin/categories/new'
    | '/admin/kyc/$kycId'
    | '/admin/plans/new'
    | '/admin/products/new'
    | '/admin/wallets/new'
    | '/dashboard/account/profile'
    | '/dashboard/account/wallet'
    | '/admin/categories'
    | '/admin/kyc'
    | '/admin/plans'
    | '/admin/products'
    | '/admin/users'
    | '/admin/wallets'
    | '/dashboard/account'
    | '/dashboard/deposit'
    | '/dashboard/transfer'
    | '/dashboard/withdraw'
    | '/admin/plans/edit/$planId'
    | '/admin/products/edit/$productId'
    | '/dashboard/account/invest/$planId'
    | '/dashboard/account/kyc/approved'
    | '/dashboard/account/kyc/not-submitted'
    | '/dashboard/account/kyc/pending'
    | '/dashboard/account/kyc/rejected'
    | '/dashboard/account/kyc'
    | '/dashboard/account/liquidate'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/buy-crypto'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/our-team'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/deposits'
    | '/admin/investments'
    | '/admin/liquidations'
    | '/admin/transfers'
    | '/admin/withdrawals'
    | '/dashboard/all-history'
    | '/dashboard/deposit-history'
    | '/dashboard/investment-history'
    | '/dashboard/liquidation-history'
    | '/dashboard/notifications'
    | '/dashboard/plans'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/transfer-history'
    | '/dashboard/withdraw-history'
    | '/ref/$refId'
    | '/admin/'
    | '/dashboard/'
    | '/admin/categories/new'
    | '/admin/kyc/$kycId'
    | '/admin/plans/new'
    | '/admin/products/new'
    | '/admin/wallets/new'
    | '/dashboard/account/profile'
    | '/dashboard/account/wallet'
    | '/admin/categories/'
    | '/admin/kyc/'
    | '/admin/plans/'
    | '/admin/products/'
    | '/admin/users/'
    | '/admin/wallets/'
    | '/dashboard/account/'
    | '/dashboard/deposit/'
    | '/dashboard/transfer/'
    | '/dashboard/withdraw/'
    | '/admin/plans/edit/$planId'
    | '/admin/products/edit/$productId'
    | '/dashboard/account/invest/$planId'
    | '/dashboard/account/kyc/approved'
    | '/dashboard/account/kyc/not-submitted'
    | '/dashboard/account/kyc/pending'
    | '/dashboard/account/kyc/rejected'
    | '/dashboard/account/kyc/'
    | '/dashboard/account/liquidate/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BuyCryptoRoute: typeof BuyCryptoRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OurTeamRoute: typeof OurTeamRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  RefRefIdRoute: typeof RefRefIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BuyCryptoRoute: BuyCryptoRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OurTeamRoute: OurTeamRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  RefRefIdRoute: RefRefIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/dashboard",
        "/about",
        "/buy-crypto",
        "/contact",
        "/faqs",
        "/forgot-password",
        "/our-team",
        "/reset-password",
        "/sign-in",
        "/sign-up",
        "/ref/$refId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/deposits",
        "/admin/investments",
        "/admin/liquidations",
        "/admin/transfers",
        "/admin/withdrawals",
        "/admin/",
        "/admin/categories/new",
        "/admin/kyc/$kycId",
        "/admin/plans/new",
        "/admin/products/new",
        "/admin/wallets/new",
        "/admin/categories/",
        "/admin/kyc/",
        "/admin/plans/",
        "/admin/products/",
        "/admin/users/",
        "/admin/wallets/",
        "/admin/plans/edit/$planId",
        "/admin/products/edit/$productId"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/all-history",
        "/dashboard/deposit-history",
        "/dashboard/investment-history",
        "/dashboard/liquidation-history",
        "/dashboard/notifications",
        "/dashboard/plans",
        "/dashboard/referrals",
        "/dashboard/settings",
        "/dashboard/transfer-history",
        "/dashboard/withdraw-history",
        "/dashboard/",
        "/dashboard/account/profile",
        "/dashboard/account/wallet",
        "/dashboard/account/",
        "/dashboard/deposit/",
        "/dashboard/transfer/",
        "/dashboard/withdraw/",
        "/dashboard/account/invest/$planId",
        "/dashboard/account/kyc/approved",
        "/dashboard/account/kyc/not-submitted",
        "/dashboard/account/kyc/pending",
        "/dashboard/account/kyc/rejected",
        "/dashboard/account/kyc/",
        "/dashboard/account/liquidate/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/buy-crypto": {
      "filePath": "buy-crypto.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/faqs": {
      "filePath": "faqs.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/our-team": {
      "filePath": "our-team.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/admin/deposits": {
      "filePath": "admin/deposits.tsx",
      "parent": "/admin"
    },
    "/admin/investments": {
      "filePath": "admin/investments.tsx",
      "parent": "/admin"
    },
    "/admin/liquidations": {
      "filePath": "admin/liquidations.tsx",
      "parent": "/admin"
    },
    "/admin/transfers": {
      "filePath": "admin/transfers.tsx",
      "parent": "/admin"
    },
    "/admin/withdrawals": {
      "filePath": "admin/withdrawals.tsx",
      "parent": "/admin"
    },
    "/dashboard/all-history": {
      "filePath": "dashboard/all-history.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/deposit-history": {
      "filePath": "dashboard/deposit-history.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/investment-history": {
      "filePath": "dashboard/investment-history.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/liquidation-history": {
      "filePath": "dashboard/liquidation-history.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/notifications": {
      "filePath": "dashboard/notifications.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/plans": {
      "filePath": "dashboard/plans.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/referrals": {
      "filePath": "dashboard/referrals.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/transfer-history": {
      "filePath": "dashboard/transfer-history.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/withdraw-history": {
      "filePath": "dashboard/withdraw-history.tsx",
      "parent": "/dashboard"
    },
    "/ref/$refId": {
      "filePath": "ref/$refId.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/admin/categories/new": {
      "filePath": "admin/categories/new.tsx",
      "parent": "/admin"
    },
    "/admin/kyc/$kycId": {
      "filePath": "admin/kyc/$kycId.tsx",
      "parent": "/admin"
    },
    "/admin/plans/new": {
      "filePath": "admin/plans/new.tsx",
      "parent": "/admin"
    },
    "/admin/products/new": {
      "filePath": "admin/products/new.tsx",
      "parent": "/admin"
    },
    "/admin/wallets/new": {
      "filePath": "admin/wallets/new.tsx",
      "parent": "/admin"
    },
    "/dashboard/account/profile": {
      "filePath": "dashboard/account/profile.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/wallet": {
      "filePath": "dashboard/account/wallet.tsx",
      "parent": "/dashboard"
    },
    "/admin/categories/": {
      "filePath": "admin/categories/index.tsx",
      "parent": "/admin"
    },
    "/admin/kyc/": {
      "filePath": "admin/kyc/index.tsx",
      "parent": "/admin"
    },
    "/admin/plans/": {
      "filePath": "admin/plans/index.tsx",
      "parent": "/admin"
    },
    "/admin/products/": {
      "filePath": "admin/products/index.tsx",
      "parent": "/admin"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    },
    "/admin/wallets/": {
      "filePath": "admin/wallets/index.tsx",
      "parent": "/admin"
    },
    "/dashboard/account/": {
      "filePath": "dashboard/account/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/deposit/": {
      "filePath": "dashboard/deposit/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/transfer/": {
      "filePath": "dashboard/transfer/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/withdraw/": {
      "filePath": "dashboard/withdraw/index.tsx",
      "parent": "/dashboard"
    },
    "/admin/plans/edit/$planId": {
      "filePath": "admin/plans/edit/$planId.tsx",
      "parent": "/admin"
    },
    "/admin/products/edit/$productId": {
      "filePath": "admin/products/edit/$productId.tsx",
      "parent": "/admin"
    },
    "/dashboard/account/invest/$planId": {
      "filePath": "dashboard/account/invest/$planId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/kyc/approved": {
      "filePath": "dashboard/account/kyc/approved.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/kyc/not-submitted": {
      "filePath": "dashboard/account/kyc/not-submitted.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/kyc/pending": {
      "filePath": "dashboard/account/kyc/pending.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/kyc/rejected": {
      "filePath": "dashboard/account/kyc/rejected.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/kyc/": {
      "filePath": "dashboard/account/kyc/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/account/liquidate/": {
      "filePath": "dashboard/account/liquidate/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
